//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"strings"

	"gopkg.in/yaml.v2"
)

type ActorType struct {
	Name string `yaml:"name"`
}

type Config struct {
	ActorTypes []ActorType `yaml:"actor_types"`
}

func main() {
	// 读取 YAML 文件
	yamlFile, err := ioutil.ReadFile("actor_types.yml")
	if err != nil {
		log.Fatalf("Error reading YAML file: %v", err)
	}

	var config Config
	err = yaml.Unmarshal(yamlFile, &config)
	if err != nil {
		log.Fatalf("Error parsing YAML: %v", err)
	}

	// 准备 Go 代码
	var code strings.Builder
	code.WriteString(`// Code generated by go generate; DO NOT EDIT.

package config

const (
`)

	// 生成常量
	for _, actor := range config.ActorTypes {
		constName := "ACTOR_" + strings.ToUpper(actor.Name)
		code.WriteString(fmt.Sprintf("    %s = \"%s\"\n", constName, actor.Name))
	}

	code.WriteString(")\n")

	// 写入文件
	err = ioutil.WriteFile("actor_types.go", []byte(code.String()), 0644)
	if err != nil {
		log.Fatalf("Error writing to file: %v", err)
	}

	fmt.Println("config/actor_types.go has been generated successfully.")
}
